version: '3.10'

services:
  vllmapiserver:
    image: llm-api:vllm
    command: python api/server.py
    ulimits:
      stack: 67108864
      memlock: -1
    environment:
      - PORT=8000
      - MODEL_NAME=qwen2
      - PROMPT_NAME=qwen2
      - MODEL_PATH=checkpoints/Qwen2-7B-Instruct
#      - EMBEDDING_NAME=checkpoints/bce-embedding-base_v1
    volumes:
      - $PWD:/workspace
      # model path need to be specified if not in pwd
#      - /data/checkpoints:/workspace/checkpoints
    env_file:
      - .env.vllm.example
    ports:
      - "7891:8000"
    restart: always
    networks:
      - vllmapinet
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']  # 指定gpu
              capabilities: [gpu]

networks:
  vllmapinet:
    driver: bridge
    name: vllmapinet